### ISSUE TITLE
Tensorflow-gpu libcublas.so.10.0 Import Error

### ISSUE THREAD

**Issue by ridago** [RSE-Sheffield/GPUComputing#16]
I have followed the instructions here: http://docs.iceberg.shef.ac.uk/en/latest/sharc/software/apps/tensorflow.html to try to get tensorflow-gpu working. I logged in to an interactive session using qrsh -l gpu=1 and followed the guide exactly except using a different name for my conda environment. When I run the test script I get the following error:

`Traceback (most recent call last):
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import tensorflow as tf
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/coa14fr/.conda/envs/ap_env/lib/python3.6/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory`

My best guess is that the newest tensorflow-gpu version expects CUDA 10.0, but the version on SHARC is 9.0?

**Comment by ptheywood** [comment]
As you suspect a new version of tensorflow-gpu has been uploaded to pypy (1.13.1, Feb 26), which now uses CUDA 10.0 rather than CUDA 9.0. 

Currently, CUDA 10.0 is not installed on ShARC. I have placed a request for this to be installed (along with CUDA 10.1) and so it will become available in the near future. Upgrading the CUDA version requires a driver update and a node-reboot, so this will not be an immediate process. 

For now, you should be able to install the older version of `tensorflow-gpu`

I.e 
```
pip install tensorflow-gpu==1.12.0
```

**Comment by ptheywood** [comment]
CUDA 10.0 and CUDNN 7.5 with CUDA 10.0 are now available on ShARC. 

Using the latest version of `tensorflow-gpu` now works using the module `libs/cudnn/7.5.0.56/binary-cuda-10.0.130`

The ShARC documentation has been updated to reflect this 
http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/tensorflow.html#cuda-and-cudnn-import-errors
