### ISSUE TITLE
ResourceExhaustedError: OOM when allocating tensor

### ISSUE THREAD

**Issue by peterkentish** [RSE-Sheffield/GPUComputing#17]
Hi, 

I am running a neural network training procedure and it keeps crashing out with this error. The cause i understand, it is saying it is running out of memory, but the email log says `Max vmem         = 4.177G` . The GPUs are 12GB in RAM I thought, so not sure what is quite happening here. I'm sure its probably some setting somewhere, any help appreciated! 

See below for full traceback. 

The batch job requests:
```
#!/bin/bash
#$ -j y
#$ -l gpu=1 
#$ -l rmem=16G

# Email notifications to me@somedomain.com
#$ -M pkentishdelaiglesia1@shef.ac.uk
# Email notifications if the job aborts
#$ -m aeb
```

The tensorflow discovery of the GPU:

```
2019-04-12 19:29:29.593850: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:06:00.0
Total memory: 11.17GiB
Free memory: 437.44MiB
```

And finally the full traceback:
```
Traceback (most recent call last):
  File "logo_wgan.py", line 653, in <module>
    wgan.train()
  File "logo_wgan.py", line 591, in train
    self.t_train: True})
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[32,128,32,32]
	 [[Node: mul_53 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape_40, ones_50)]]
	 [[Node: div_9/_235 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_7155_div_9", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'mul_53', defined at:
  File "logo_wgan.py", line 653, in <module>
    wgan.train()
  File "logo_wgan.py", line 415, in train
    is_training=self.t_train),
  File "/data/aca15pk/University/Test2/logo-gen-master/wgan/tflib/architectures.py", line 30, in Generator_Resnet_32
    is_training=is_training)
  File "/data/aca15pk/University/Test2/logo-gen-master/wgan/tflib/ops/gan_ops.py", line 143, in ResidualBlock
    output = tflib.ops.concat.conv_cond_concat(output, yb)
  File "/data/aca15pk/University/Test2/logo-gen-master/wgan/tflib/ops/concat.py", line 13, in conv_cond_concat
    return concat([x, y*tf.ones([x_shape[0], y_shape[1], x_shape[2], x_shape[3]])], 1)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 865, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1088, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1449, in _mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aca15pk/.conda/envs/py2-gpu/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[32,128,32,32]
	 [[Node: mul_53 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape_40, ones_50)]]
	 [[Node: div_9/_235 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_7155_div_9", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

**Comment by ptheywood** [comment]
```
Total memory: 11.17GiB
Free memory: 437.44MiB
```
Indicates that this GPU only had 437MiB of it's 11.17 GiB of ram available. 

Due to scheduler limitations the public GPUs do not assign individual devices to individual users. This means that by default everyone on the same node will attempt to use the same GPU (GPU 0). 

You might be able to resolve this by selecting a device which is not being used, using the `CUDA_VISIBLE_DEVICES` environment variable. 

I've written a script which will attempt to select the best device to use:

https://gist.github.com/ptheywood/ce4e5a600216dd085cae5bd5802d35aa

Either copy/paste lines 3 to 80 into your job submission script, and add:

```
setCUDAVisibileDevices $(getSGERequestedGPUCount)
```

Or save the script to somewhere on ShARC and include it by reference, before calling the above function.

This *should* assign a device which no one else is using, assuming others are only using the number of GPUs they requested.


Note that re-setting CUDA_VISIBLE_DEVICES should not be used on the private nodes in ShARC, which do allocate individual devices.
